language: ruby
rvm:
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2" # latest 2.2.x
  - "2.3.0"
  - "2.4.0"
  - "jruby-9.1.5.0"
  - "jruby-head"
script:
  bundle exec rake test
sudo: false

before_install:
  # get latest rubygems due to weird bugs
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

env:
  # avoid jruby unknown property jruby.cext.enabled
  # https://github.com/travis-ci/travis-ci/issues/6471
  - JRUBY_OPTS=''
